version: '3.5'

services:

  db:
    container_name: postgres_container
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB} 
      PGDATA: /tmp
    volumes:
       - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks: 
      - postgres
    restart: unless-stopped 

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres

  localstack:
    container_name: "localstack"
    image: localstack/localstack:0.14.4
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "9090:8080"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "./docker/localstack/localstack:/tmp/localstack"
      - "./docker/localstack/mercanis:/tmp/mercanis-localstack"
      - "./docker/localstack/docker:/var/run/docker.sock"

networks:
  postgres:
    driver: bridge
