###
POST http://localhost:3000/auth/login
Content-Type: application/json

{"username": "john", "password": "changeme"}

###
GET http://localhost:3000/restaurant/
Content-Type: application/json
Authorization: Braia aewoJImlkIjogIjEyM2FiYyIsCgkibmFtZSI6ICJub21lIgp9

###
GET http://localhost:3000/restaurant/2
Content-Type: application/json
Authorization: Braia ewoJImlkIjogIjEyM2FiYyIsCgkibmFtZSI6ICJub21lIgp9

###
DELETE  http://localhost:3000/restaurant/5
Content-Type: application/json
Authorization: Braia ewoJImlkIjogIjEyM2FiYyIsCgkibmFtZSI6ICJub21lIgp9

###
POST http://localhost:3000/restaurant
Content-Type: application/json
Authorization: Braia ewoJImlkIjogIjEyM2FiYyIsCgkibmFtZSI6ICJub21lIgp9

{
    "description": "description",
    "address": {
        "description": "description",
        "number": "number"
    }
}


###
POST http://localhost:3000/order
Content-Type: application/json
Authorization: Braia ewoJImlkIjogIjEyM2FiYyIsCgkibmFtZSI6ICJub21lIgp9

{
    "restaurantId": "1",
    "description": "description"
}


###
GET http://localhost:3000/order/restaurant/1
Content-Type: application/json
Authorization: Braia ewoJImlkIjogIjEyM2FiYyIsCgkibmFtZSI6ICJub21lIgp9
